name: Build and Test with Magento 2.4

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']
        magento-versions: ['2.4.4']

    services:
      mysql:
        image: mysql:8.0.20
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, gd, bcmath, ctype, curl, dom, hash, iconv, intl, openssl, simplexml, soap, xsl, zip
          tools: composer:v2
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.6.0

      - name: PHP Syntax Checker
        run: find . -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )

      - name: Setup Magento 2 and run tests
        run: |
          mysql -u root --password=root -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS magento;'
          git clone --depth=1 -b ${{ matrix.magento-versions }} https://github.com/magento/magento2 /tmp/build
          cd /tmp/build
          composer update
          php bin/magento setup:install --base-url=http://magebuild.integrations.p1-test.de/build/ \
          --db-host=127.0.0.1 --db-name=magento --db-user=root --db-password=root --admin-firstname=Dieter \
          --admin-lastname=Demo --admin-email=dieterdemo@payone.com --admin-user=DieterDemo \
          --admin-password=72q980hdfq2378ga9w87dg6 --language=de_DE --currency=EUR --timezone=Europe/Berlin \
          --search-engine=elasticsearch7 --elasticsearch-host=localhost \
          --elasticsearch-port=9200
          composer require --ignore-platform-reqs payone-gmbh/magento-2 dev-master
          rm -rf /tmp/build/vendor/payone-gmbh/magento-2/*
          cp -R $GITHUB_WORKSPACE/* /tmp/build/vendor/payone-gmbh/magento-2
          php bin/magento setup:upgrade
          php bin/magento setup:di:compile
          php bin/magento cache:clean
          ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist vendor/payone-gmbh/magento-2/Test/Unit

